export enum MongooseDbProviders {
    CARD_ADAPTER = "CARD_ADAPTER", 
    CARD_SERVICE = "CARD_SERVICE",
    CARD_EVENT_ADAPTER = "CARD_EVENT_ADAPTER",
    CARD_EVENT_SERVICE = "CARD_EVENT_SERVICE",
    USER_ADAPTER = "USER_ADAPTER",
    USER_SERVICE = "USER_SERVICE",
}