export enum MongooseDbProviders {
    CARD_ADAPTER = "CARD_ADAPTER", 
    CARD_SERVICE = "CARD_SERVICE",
    CARD_EVENT_ADAPTER = "CARD_EVENT_ADAPTER",
    CARD_EVENT_SERVICE = "CARD_EVENT_SERVICE",
    LOBBY_ADAPTER = "LOBBY_ADAPTER",
    LOBBY_SERVICE = "LOBBY_SERVICE",
    LOBBY_USER_ADAPTER = "LOBBY_USER_ADAPTER",
    LOBBY_USER_SERVICE = "LOBBY_USER_SERVICE",
    USER_ADAPTER = "USER_ADAPTER",
    USER_SERVICE = "USER_SERVICE",
}