export enum CardType {
    SPELL_CASTER = "Spell Caster",
    DRAGON = "Dragon",
    ZOMBIE = "Zombie",
    WARRIOR = "Warrior",
    BEAST_WARRIOR = "Beast Warrior",
    BEAST = "Beast",
    WINGED_BEAST = "Winged Beast",
    FIEND = "Fiend",
    FAIRY = "Fairy",
    INSECT = "Insect",
    DINOSAUR = "Dinosaur",
    REPTILE = "Reptile",
    SEA_SERPENT = "Sea Serpent",
    AQUA = "Aqua",
    PYRO = "Pyro",
    THUNDER = "Thunder",
    ROCK = "Rock",
    PLANT = "Plant",
    MACHINE = "Machine",
    PSYCHIC = "Psychic",
    DIVINE_BEAST = "Divine Beast",
    WYRM = "Wyrm",
    CYBERSE = "Cyberse",
    ILLUSION = "Ilusion" 
}